spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    group:
      "local": "localPort, localDB, localJPA, web-mvc"
      "dev": "devPort, devDB, devJPA, web-mvc"
      "prod": "devPort, devDB, prodJPA, web-mvc"
---
spring:
  config:
    activate:
      on-profile: "devPort"

server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: "devDB"

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.hibernate.sql: debug
---
spring:
  config:
    activate:
      on-profile: "devJPA"

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: "prodJPA"

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: "web-mvc"

  web:
    resources:
      add-mappings: false

  messages:
    basename: errors
---
# Actuator 모니터링 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  security:
    enabled: false
